### PR TITLE
Check whether GraphViz is installed, instead of having unhandled exce…

### PR DESCRIPTION
**Pull request by mmzx**
…ption.

### CODE REVIEW

**Comment by zhujinxuan** [comment]
@mmzx Hi, is this a work in process PR or a finished PR?

**Comment by mmzx** [comment]
It is indeed a finished one. When others are available/involved I prefer to hear the voices. :)

**Comment by zhujinxuan** [comment]
how about `ifM` from `Control.Monad.Extra` or 

```
checkRequirements = (isGraphvizInstalled >>= guard) <|> quitWithoutGraphviz message where
   message =   "GraphViz is not installed on your system.\n" ++  "Please install it first, https://github.com/BurntSushi/erd"
```

**Comment by mmzx** [comment]
Right. Nicer code.

**Comment by zhujinxuan** [comment]
Hi, @mmzx Can you use squash and merge in merging a PR next time;  It will let you edit the commit message and gives a neater commit history.

screenshot 2019-02-16 14 30 16

An example given by the squash and merge:
screenshot 2019-02-16 14 32 36

**Pull request merged**
