### PR TITLE
Added option to select the type of the edges

### PR DESCRIPTION
**Pull request by fgaray**
This PR allow the user to select different types of edges from the options available in graphviz

### CODE REVIEW

**Comment by mmzx** [comment]
I have just created this [gist](https://gist.github.com/mmzx/89d79c8585eba3491e61bd9a87f8a404) which shows how the available and different type of edges perform utilizing the pull-request.
I personally would not support:

- curved
- line

Even _noedge_ I do find useful for certain purposes. Overall I like this feature and would like to have it accepted with the above mentioned modifications.

**Comment by mmzx** [comment]
I have merged this PR successfully and on top of that removed support for _curved_ and _line_ type of edges. Please approve it, then I will push it to **master**.

**Comment by zhujinxuan** [comment]
@mmzx Will you add examples in `examples` to show how it will work?

**Comment by zhujinxuan** [comment]
Oh I see.  I works by `erd --edge Edge`, right?

**Comment by mmzx** [comment]
Created #54 that incorporates the additional changes.

**Pull request merged**
